# Generated by Django 3.1 on 2021-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='path',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
