# Generated by Django 3.1 on 2021-03-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0002_auto_20210316_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='path',
            field=models.ImageField(upload_to='imagelist/'),
        ),
    ]
