# Generated by Django 3.1 on 2021-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0003_auto_20210316_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
    ]
